export const COUNT_MORE_CHEESE = "COUNT_MORE_CHEESE"
export const COUNT_MORE_CHICKEN = "COUNT_MORE_CHICKEN"
export const COUNT_MORE_ONIONS = "COUNT_MORE_ONIONS"

export const COUNT_LESS_CHEESE = "COUNT_LESS_CHEESE"
export const COUNT_LESS_CHICKEN = "COUNT_LESS_CHICKEN"
export const COUNT_LESS_ONIONS = "COUNT_LESS_ONIONS"

export const COUNT_RESET = "COUNT_RESET"